on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

name: Test

jobs:
  test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
        name: Checkout 🛎️
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-test
      - uses: actions-rs/toolchain@v1
        name: Setup Cargo Toolchain 🛎️
        with:
          components: rustfmt, clippy
          toolchain: nightly
          default: true
      - uses: actions-rs/cargo@v1
        name: Check Code Format 🔧
        with:
          command: fmt
          args: -- --check
      - uses: actions-rs/cargo@v1
        name: Linting The Code 🩹
        with:
          command: clippy
          args: --all-targets --all-features --workspace
      - uses: actions-rs/cargo@v1
        name: Running Tests 🚀
        with:
          command: test
          args: --all-features --workspace
  sanitizer_test:
    name: Test with Sanitizer
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sanitizer: ["address", "leak", "memory", "thread"]
    steps:
      - uses: actions/checkout@v2
        name: Checkout 🛎️
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.sanitizer }}-cargo-sanitizer-test
      - uses: actions-rs/toolchain@v1
        name: Setup Cargo Toolchain 🛎️
        with:
          components: rustfmt, clippy, rust-src
          toolchain: nightly
          default: true
      - uses: actions-rs/cargo@v1
        name: Running Tests with ${{ matrix.sanitizer }} sanitizer 🚀
        with:
          command: test
          args: --all-features -Zbuild-std --target x86_64-unknown-linux-gnu
        env:
          RUSTFLAGS: "-Zsanitizer=${{ matrix.sanitizer }}"
